name: Deploy book
on:
  push:
  workflow_dispatch:
env:
  MDBOOK_VERSION: 0.5.1
  MDBOOK_MERMAID_VERSION: 0.17.0
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: mdbook@0.5.3
      - name: Install mdbook-linkcheck
        uses: baptiste0928/cargo-install@v3
        # Temporarily pull the fix for https://github.com/Michael-F-Bryan/mdbook-linkcheck/pull/98
        with:
          crate: mdbook-linkcheck
          git: https://github.com/schilkp/mdbook-linkcheck
          rev: ed981be6ded11562e604fff290ae4c08f1c419c5
      - name: Build the book
        run: |
          mdbook build
          touch book/html/.nojekyll
      - name: Upload book
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book/html
  deploy:
    if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
    concurrency:
      group: "pages"
      cancel-in-progress: false
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy book
        id: deployment
        uses: actions/deploy-pages@v4
